services:
  ldap:
    image: glauth/glauth:v2.4.0
    volumes:
      - ./config/glauth.conf:/app/config/config.cfg:ro
    labels:
      - traefik.http.services.ldap.loadbalancer.server.port=5555
    post_start:
      # "Install" busybox netcat for healthchecks
      - command: /usr/bin/cp /bin/sh /bin/nc
    healthcheck:
      test: /bin/nc -zv 127.0.0.1 3893
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
