services:
  backend:
    platform: linux/amd64
    image: ghcr.io/scicatproject/backend:latest
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./config/config.local.js:/home/node/app/server/config.local.js
      - ./config/datasources.json:/config/datasources.0.json
      - ./config/providers.json:/config/providers.json
      - ${PWD}/entrypoints/loop_entrypoints.sh:/usr/local/bin/loop_entrypoints.sh
      - ./entrypoints/merge_json.sh:/docker-entrypoints/0.sh
    entrypoint:
      - loop_entrypoints.sh
      - docker-entrypoint.sh
    command: node .
    healthcheck:
      test: wget --spider 'http://127.0.0.1:3000/'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
