services:
  jupyter:
    platform: linux/amd64
    image: quay.io/jupyter/base-notebook:x86_64-notebook-7.1.2
    depends_on:
      backend:
        condition: service_healthy
    labels:
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
    configs:
      - source: jupyter_requirements_txt
        target: /home/jovyan/requirements.txt
      - source: jupyter_notebook_pyscicat_ipynb
        target: /home/jovyan/notebooks/pyscicat.ipynb
      - source: jupyter_notebook_thumbnail_png
        target: /home/jovyan/notebooks/example_files/thumbnail.png
    env_file:
      - config/.env
    environment:
      BE_VERSION: ${BE_VERSION:-v4}
    profiles:
      - analysis
    restart: on-failure

configs:
  jupyter_requirements_txt:
    file: ./config/requirements.txt
  jupyter_notebook_pyscicat_ipynb:
    file: ./config/notebooks/pyscicat.ipynb
  jupyter_notebook_thumbnail_png:
    file: ./config/notebooks/example_files/thumbnail.png
