yaml:
  - '**.yml'
  - '**.yaml'
js:
  - '**.js'
  - '**.ts'
  - '**.cjs'
  - '**.mjs'
  - '**.html'
sh:
  - '**.sh'
json:
  - '**.json'
python:
  - '**.py'
src: &src
  - '!LICENSE'
  - '!**/*.md'
  - '!CODEOWNERS'
  - '!**/*mkdocs*/**'
  - '!**/*mkdocs*'
ldap:
  - '**/ldap/**'
  - '**/*ldap*'
  - *src
oidc:
  - '**/*oidc*'
  - '**/keycloak/**'
  - '**/*keycloak*'
  - *src
v3: &v3
  - '**/v3/**'
  - '**/*v3*'
  - services/compose.dev.yaml
  - *src
v4: &v4
  - '**/v4/**'
  - '**/*v4*'
  - *src
  - services/compose.dev.yaml
jobs: &jobs
  - '**/rabbitmq/**'
  - '**/*jobs*'
  - '**/archivemock/**'
  - *src
elastic: &elastic
  - '**/elastic/**'
  - '**/*elastic*'
  - *src
other_scicat: &other_scicat
  - services/searchapi/**
  - services/landingpage/**
  - services/frontend/**
  - services/oaipmh/**
docs:
  - '**/README.md'
  - '**/*mkdocs*/**'
  - '**/*mkdocs*'
  - '**/*markdownlint*'
  - '**/*markdownlint*/**'
dev:
  - '**/*dev*'
  - '**/entrypoints/**'
  - *v3
  - *v4
  - *elastic
  - *jobs
  - *other_scicat
