yaml:
  - '**.yml'
  - '**.yaml'
js:
  - '**.js'
  - '**.ts'
  - '**.cjs'
  - '**.mjs'
sh:
  - '**.sh'
json:
  - '**.json'
src: &src
  - '!**/*.md'
  - '!**/mkdocs/*'
  - '!**/*mkdocs*'
ldap:
  - '**/ldap/**'
  - '**/*ldap*'
  - *src
oidc:
  - '**/*oidc*'
  - '**/keycloak/**'
  - '**/*keycloak*'
  - *src
dev:
  - '**/*dev*'
  - *src
v3:
  - '**/v3/**'
  - '**/*v3*'
  - *src
v4:
  - '**/v4/**'
  - '**/*v4*'
  - *src
ej:
  - '**/archivemock/**'
  - '**/rabbitmq/**'
  - '**/*jobs*'
  - '**/elastic/**'
  - '**/*elastic*'
  - *src
