src:
  - '**/**'
  - '!LICENSE'
  - '!**/*.md'
  - '!CODEOWNERS'
  - '!**/*mkdocs*/**'
  - '!**/*mkdocs*'
v3: &v3
  - '**/v3/**'
  - '**/*v3*'
  - '!**/*.md'
  - entrypoints/npm_ci.sh
  - entrypoints/loop_entrypoints.sh
jobs: &jobs
  - '**/rabbitmq/**'
  - '**/*jobs*'
  - '**/archivemock/**'
  - '!**/*.md'
opensearch: &opensearch
  - '**/opensearch/**'
  - '**/*opensearch*'
  - '!**/*.md'
ldap:
  - '**/ldap/**'
  - '**/*ldap*'
  - '!**/*.md'
oidc:
  - '**/*oidc*'
  - '**/keycloak/**'
  - '**/*keycloak*'
  - '!**/*.md'
other_scicat: &other_scicat
  - services/searchapi/**
  - services/landingpage/**
  - services/frontend/**
  - services/oaipmh/**
  - '**/v4/**'
  - '**/*v4*'
  - '!**/*.md'
docs_service: &docs_service
  - services/docs/**
  - '!services/docs/**/README.md'
dev:
  - '**/*dev*'
  - '**/entrypoints/**'
  - *v3
  - *opensearch
  - *jobs
  - *other_scicat
  - *docs_service
