services:
  lintci:
    image: efrecon/act:v0.2.89
    platform: linux/amd64
    working_dir: /repo
    depends_on:
      lint:
        condition: service_completed_successfully
    volumes:
      - ${PWD}:/repo
      - /var/run/docker.sock:/var/run/docker.sock
      - act_cache:/root/.cache/act
    command:
      - pull_request
      - -W
      - .github/workflows/compose_test.yaml
      - -j
      - ${JOB:-lint}
      - -P
      - ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
      - --local-repository
      - SciCatProject/scicatlive@main=/repo
      - --env-file
      - /dev/null

  lint:
    image: ghcr.io/catthehacker/ubuntu:act-latest
    working_dir: /repo
    volumes:
      - ${PWD}:/repo
      - ${PWD}/entrypoints/loop_entrypoints.sh:/usr/local/bin/loop_entrypoints.sh:ro
      - ./lint/ruff.sh:/docker-entrypoints/10.sh:ro
      - ./lint/eslint.sh:/docker-entrypoints/20.sh:ro
      - ./lint/markdownlint.sh:/docker-entrypoints/30.sh:ro
      - ./lint/publish-oci-tests.sh:/docker-entrypoints/40.sh:ro
    environment:
      FIX_FLAG: ${FIX:+--fix}
    entrypoint:
      - loop_entrypoints.sh

volumes:
  act_cache:
    driver: local
