include:
  - services/backend/compose.yaml
  - services/frontend/compose.yaml
  - services/searchapi/compose.yaml
  - services/proxy/compose.yaml
  - services/jupyter/compose.yaml
  - services/landingpage/compose.yaml
  - services/oaipmh/compose.yaml

configs:
  web_app_loop_entrypoints_sh:
    file: ./entrypoints/loop_entrypoints.sh
  web_app_infinite_loop_sh:
    file: ./entrypoints/infinite_loop.sh
  web_app_bidirectional_backup_sh:
    file: ./entrypoints/bidirectional_backup.sh
  web_app_chown_root_sh:
    file: ./entrypoints/chown_root.sh
  web_app_add_dev_deps_sh:
    file: ./entrypoints/add_dev_deps.sh
  web_app_setup_git_sh:
    file: ./entrypoints/setup_git.sh
