services:
  searchapi:
    platform: linux/amd64
    image: ghcr.io/scicatproject/panosc-search-api:latest
    depends_on:
      - backend
    env_file:
      - ./config/.env
    profiles:
      - search
