services:
  searchapi:
    platform: linux/amd64
    image: ghcr.io/scicatproject/panosc-search-api:latest
    depends_on:
      - backend
    env_file:
      - ./config/.env
    labels:
      # Adding a label to keep this service out of traefik
      - traefik.enable=false
    profiles:
      - search
    restart: on-failure
