services:
  searchapi:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-local
    configs:
      - source: entrypoints_npm_ci_sh
        target: /docker-entrypoints/10.sh
        mode: 0555
    env_file:
      - ./config/.dev.env

volumes:
  searchapi_dev:
    driver: local
