services:
  searchapi:
    image: ghcr.io/scicatproject/panosc-search-api:latest
    depends_on:
      - backend
    labels:
      - traefik.http.routers.searchapi.rule=Host(`${SEARCH_HOST}`)
      - traefik.http.routers.searchapi.entrypoints=${ROUTER_ENTRYPOINTS}
    env_file:
      - ./config/.env
