services:
  frontend:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-remote
    build:
      target: builder
    environment:
      CONFIG_DIR: ${WORKDIR}/src/assets
      CHROME_BIN: /usr/bin/chromium
    volumes:
      - ${PWD}/entrypoints/merge_json.sh:/docker-entrypoints/10.sh
      - ${PWD}/entrypoints/add_chrome.sh:/docker-entrypoints/20.sh
    post_start: !reset null

volumes:
  frontend_dev:
    driver: local
