include:
  - ../keycloak/compose.yaml

services:
  backend:
    depends_on:
      keycloak:
        condition: service_healthy
    links:
      - keycloak:keycloak.localhost
    volumes:
      - ./config/providers.oidc.json:/config/providers.oidc.json
      - ./config/login-callbacks.js:/home/node/app/server/boot/login-callbacks.js
    environment:
      OIDC_ENABLED: true
      BACKEND_URL: ${BACKEND_HTTPS_URL:-http://backend.localhost}
      FRONTEND_URL: ${FRONTEND_HTTPS_URL:-http://localhost}
      KEYCLOAK_URL: ${KEYCLOAK_HTTPS_URL:-http://keycloak.localhost}
