services:
  docs:
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - type: volume
        source: ${_BE_VERSION}_dev
        target: /docs/backend
        read_only: true
        volume:
          subpath: docs
