include:
  - path:
      - .${_DOCS_DEV:+/}compose.base.yaml
      - .${_BACKEND_DEV:+/}compose.backend.${_BE_VERSION}.yaml
      - .${_FRONTEND_DEV:+/}compose.frontend.yaml
      - .${_SCICATLIVE_DEV:+/}compose.scicatlive.yaml
      - .${_USER_DOCS_DEV:+/}compose.userdocs.yaml
