services:
  rabbitmq:
    image: "rabbitmq:3.13-management-alpine"
    labels:
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    volumes:
      - "rabbitmq_data:/bitnami"
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      start_period: "5s"
      interval: "30s"
      timeout: "10s"
      retries: 5

volumes:
  rabbitmq_data:
    driver: "local"
