name: mike-pages
description: Creates mike documentation from md files

inputs:
  GITHUB_TOKEN:
    description: github token
    required: true
    type: string
  TAG:
    description: commit or tag or branch for github links
    type: string
    default: ${{ github.ref_name }}
  DOCS_LINK_CHECK:
    description: string to trigger the links check
    type: string
    default: ''
  push:
    description: if to publish docs to gh-pages
    type: string
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      shell: bash
      run: |
          pip install -r .github/mkdocs/requirements.txt
    - name: Copy all to docs folder
      shell: bash
      run: |
        mkdir -p docs
        shopt -s extglob
        mv !(docs) docs/
    - name: Deploy documentation
      shell: bash
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          VERSION=$(echo ${TAG} | awk -F'.' '{print $1"."$2}')
          VERSION=${VERSION%.}
        fi

        git fetch origin gh-pages --depth=1
        PUSH=${{ inputs.push }}
        mike deploy -F ${DOCS_CONFIG} ${PUSH:+--push} \
          --update-aliases ${VERSION:-main} ${VERSION:+latest}
        mike set-default -F ${DOCS_CONFIG} --push latest
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GIT_COMMITTER_NAME: ci-bot
        GIT_COMMITTER_EMAIL: ci-bot@example.com
        DOCS_CONFIG: .github/mkdocs/mkdocs.yaml
        TAG: ${{ inputs.TAG }}
        DOCS_LINK_CHECK: ${{ inputs.DOCS_LINK_CHECK }}
