name: mike-pages
description: Creates mike documentation from md files

inputs:
  GITHUB_TOKEN:
    description: github token
    required: true
  TAG:
    description: commit or tag or branch for github links
    default: ${{ github.ref_name }}
  DOCS_LINK_CHECK:
    description: string to trigger the links check
    default: ''
  push:
    description: if to publish docs to gh-pages
    default: ''
  docs_folder:
    description: docs folder path. If empty, it checkouts all to a fresh 'docs'
    default: docs

runs:
  using: composite
  steps:
    - if: ${{ !inputs.docs_folder }}
      name: Checkout CI
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        sparse-checkout: .github
    - name: Checkout root
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      with:
        path: ${{ !inputs.docs_folder && 'docs' || '' }}
        sparse-checkout: |
          ${{ inputs.docs_folder }}
          ${{ inputs.docs_folder && '.github' }}
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
      with:
        python-version: 3.x
    - name: Install dependencies
      shell: bash
      run: |
          pip install -r .github/mkdocs/requirements.txt
    - name: Deploy documentation
      shell: bash
      run: |
        if [[ "${{ github.ref_type }}" == "tag" || \
              "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          VERSION=$(echo ${TAG} | awk -F'.' '{print $1"."$2}')
          VERSION=${VERSION%.}
        fi

        PUSH=${{ inputs.push }}
        IGNORE_REMOTE=--ignore-remote-status
        if [[ -n "$PUSH" ]]; then
          git fetch origin gh-pages --depth=1
          IGNORE_REMOTE=
        fi
        mike deploy -F ${DOCS_CONFIG} ${PUSH:+--push} $IGNORE_REMOTE \
          --update-aliases ${VERSION:-main} ${VERSION:+latest}
        mike set-default -F ${DOCS_CONFIG} ${PUSH:+--push} \
          $IGNORE_REMOTE latest ||
          mike set-default -F ${DOCS_CONFIG} ${PUSH:+--push} \
            $IGNORE_REMOTE main
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GIT_COMMITTER_NAME: ci-bot
        GIT_COMMITTER_EMAIL: ci-bot@example.com
        DOCS_CONFIG: .github/mkdocs/mkdocs.yaml
        TAG: ${{ inputs.TAG }}
        DOCS_LINK_CHECK: ${{ inputs.DOCS_LINK_CHECK }}
