include:
  - services/backend/compose.yaml
  - services/frontend/compose.yaml
  - services/searchapi/compose.yaml
  - services/proxy/compose.yaml
  - services/jupyter/compose.yaml
  - services/landingpage/compose.yaml
  - services/oaipmh/compose.yaml

configs:
  entrypoints_loop_entrypoints_sh:
    file: ./entrypoints/loop_entrypoints.sh
  entrypoints_infinite_loop_sh:
    file: ./entrypoints/infinite_loop.sh
  entrypoints_bidirectional_backup_sh:
    file: ./entrypoints/bidirectional_backup.sh
  entrypoints_chown_root_sh:
    file: ./entrypoints/chown_root.sh
  entrypoints_add_dev_deps_sh:
    file: ./entrypoints/add_dev_deps.sh
  entrypoints_setup_git_sh:
    file: ./entrypoints/setup_git.sh
  entrypoints_download_sdk_sh:
    file: ./entrypoints/download_sdk.sh
  entrypoints_merge_json_sh:
    file: ./entrypoints/merge_json.sh
  entrypoints_npm_ci_sh:
    file: ./entrypoints/npm_ci.sh
  entrypoints_add_chrome_sh:
    file: ./entrypoints/add_chrome.sh
  entrypoints_npm_install_sdk_sh:
    file: ./entrypoints/npm_install_sdk.sh
