services:
  docs:
    image: squidfunk/mkdocs-material:9.7
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    volumes:
      - ${PWD}/.github/mkdocs/:/config/github-mkdocs
      - ./entrypoints/serve.sh:/usr/local/bin/serve.sh
      - ./config/index.md:/docs/index.md
      - type: volume
        source: ${BE_VERSION:-v4}_dev
        target: /docs/backend
        read_only: true
        volume:
          subpath: docs
      - type: volume
        source: frontend_dev
        target: /docs/frontend
        read_only: true
        volume:
          subpath: docs
    restart: on-failure
    entrypoint: /usr/local/bin/serve.sh
    environment:
      GITHUB_SERVER_URL: https://github.com
      GITHUB_REPOSITORY: SciCatProject/scicatlive
      CONFIG_DIR: /config/github-mkdocs
      PYTHONDONTWRITEBYTECODE: 1
