services:
  jupyter:
    platform: linux/amd64
    image: quay.io/jupyter/base-notebook:x86_64-notebook-7.1.2
    depends_on:
      backend:
        condition: service_healthy
    labels:
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
    volumes:
      - ./config/notebooks:/home/jovyan/notebooks
      - ./config/requirements.txt:/home/jovyan/requirements.txt
    env_file:
      - config/.env
    profiles:
      - analysis
    restart: on-failure
