include:
  - services/rabbitmq/compose.yaml
  - services/archivemock/compose.yaml

services:
  backend:
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./config/component-config.local.json:/home/node/app/server/component-config.local.json
    environment:
      JOBS_ENABLED: true
