include:
  - ../keycloak/compose.yaml

services:
  backend:
    depends_on:
      keycloak:
        condition: service_healthy
    links:
      - keycloak:keycloak.localhost
    volumes:
      - ./config/providers.oidc.json:/config/providers.oidc.json
