services:
  backend:
    platform: linux/amd64
    image: ghcr.io/scicatproject/backend:latest
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./config/config.local.js:/home/node/app/server/config.local.js
      - ./config/datasources.json:/home/node/app/server/datasources.json
      - ./config/providers.json:/config/providers.json
      - ./entrypoints/init.sh:/init.sh
    command:
      - sh
      - -c
      - /init.sh && node .
    healthcheck:
      test: wget --spider 'http://127.0.0.1:3000/'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
