services:
  backend:
    platform: linux/amd64
    image: ghcr.io/scicatproject/backend:latest
    depends_on:
      mongodb:
        condition: service_started
    configs:
      - source: backend_v3_config_local_js
        target: /home/node/app/server/config.local.js
      - source: backend_v3_datasources_json
        target: /config/datasources.0.json
      - source: backend_v3_providers_json
        target: /config/providers.json
      - source: backend_v3_loop_entrypoints_sh
        target: /usr/local/bin/loop_entrypoints.sh
        mode: 0555
      - source: backend_v3_merge_json_sh
        target: /docker-entrypoints/10.sh
        mode: 0555
    entrypoint:
      - loop_entrypoints.sh
      - docker-entrypoint.sh
    command: node .
    labels:
      # Adding a label for traefik to learn which port to look for a service on
      - traefik.http.services.backend.loadbalancer.server.port=3000
    healthcheck:
      test: wget --spider 'http://127.0.0.1:3000/'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

configs:
  backend_v3_config_local_js:
    file: ./config/config.local.js
  backend_v3_datasources_json:
    file: ./config/datasources.json
  backend_v3_providers_json:
    file: ./config/providers.json
  backend_v3_loop_entrypoints_sh:
    file: ${PWD}/entrypoints/loop_entrypoints.sh
  backend_v3_merge_json_sh:
    file: ./entrypoints/merge_json.sh
