services:
  backend:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-local
    environment:
      NODE_ENV: development
    volumes:
      - ./config/settings.json:/home/node/app/test/config/settings.json
      - ./config/datasources.dev.json:/config/datasources.1.json
      - ${PWD}/entrypoints/npm_ci.sh:/docker-entrypoints/20.sh
    user: root

volumes:
  v3_dev:
    driver: local
