include:
  - ../oidc/compose.yaml

services:
  backend:
    depends_on:
      oidc:
        condition: service_healthy
    links:
      - oidc:oidc.localhost
    volumes:
      - ./config/providers.oidc.json:/config/providers.oidc.json
      - ./config/login-callbacks.js:/home/node/app/server/boot/login-callbacks.js
