services:
  web-app:
    entrypoint: loop_entrypoints.sh
    command: infinite_loop.sh
    healthcheck:
      test: pgrep -f "/bin/sh /usr/local/bin/infinite_loop.sh"
      retries: 10
    labels:
      - traefik.http.services.${APP}.loadbalancer.server.port=${DEV_PORT}
    configs:
      # These configs allow to run init scripts before running the service.
      - source: web_app_loop_entrypoints_sh
        target: /usr/local/bin/loop_entrypoints.sh
        mode: 0555
      - source: web_app_infinite_loop_sh
        target: /usr/local/bin/infinite_loop.sh
        mode: 0555
      - source: web_app_bidirectional_backup_sh
        target: /docker-entrypoints/${DEV_BBACKUP:+1}00.sh
        mode: 0555
      - source: web_app_chown_root_sh
        target: /docker-entrypoints/00.sh
        mode: 0555
      - source: web_app_add_dev_deps_sh
        target: /docker-entrypoints/01.sh
        mode: 0555
      - source: web_app_setup_git_sh
        target: /docker-entrypoints/02.sh
        mode: 0555
    environment:
      GITHUB_REPO: ${GITHUB_REPO:-}
      WORKDIR: ${WORKDIR:-/home/node/app}
      DEV_BBACKUP: ${DEV_BBACKUP:-}
    user: root
    restart: no
  node-app-from-local:
    extends: web-app
    volumes:
      # This prevents git unpushed changes from being lost on container restart
      - ${DEV_VOLUME:-${APP}}_dev:${WORKDIR:-/home/node/app}
      - ${DEV_BBACKUP:+${PWD}/bbackup/${COMPOSE_PROJECT_NAME}/${DEV_VOLUME:-${APP}}:}/bbackup
      # These allow to keep changes from npm install/build from Dockerfile CMDs
      - ${WORKDIR:-/home/node/app}/node_modules
  node-app-from-remote:
    extends: node-app-from-local
    image: ''
    build:
      context: ${GITHUB_REPO:-}
      no_cache: true
