services:
  archivemock:
    image: ghcr.io/scicatproject/archive-mock:v1.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_healthy
    env_file:
      - ./config/.env
