services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --import-realm --http-port=80
    env_file: ./config/.env
    volumes:
      - ./healthcheck/healthcheck.sh:/healthcheck.sh
      - ./config/facility-realm.json:/opt/keycloak/data/import/facility-realm.json:ro
    labels:
      - traefik.http.services.keycloak.loadbalancer.server.port=80
    healthcheck:
      test: bash /healthcheck.sh
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
