version: '2.2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    labels:
      - traefik.http.routers.elastic.rule=Host(`elastic.localhost`)
      - traefik.http.services.elastic.loadbalancer.server.port=9200
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          CMD-SHELL,
          'curl -f localhost:9200 | grep -q
            ''"tagline" : "You Know, for Search"'''
        ]
      interval: 10s
      timeout: 10s
      retries: 15
    env_file:
      - ./config/.env

volumes:
  esdata:
    driver: local
