services:
  archivemock:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: web-app
    labels: !reset null
    volumes:
      - archivemock_dev:/job_mock

volumes:
  archivemock_dev:
    driver: local
