services:
  searchapi:
    image: dacat/panosc-search-api:latest
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.searchapi.rule=PathPrefix(`/panosc-api`, `/panosc-explorer`)"
      - "traefik.http.routers.searchapi.entrypoints=web"
    env_file:
      - ./config/.env
