services:
  landingpage:
    image: ghcr.io/scicatproject/landingpageserver:v3.4
    configs:
      - source: landingpage_config_json
        target: /config/0.json
      # docker-entrypoint.d is available only in the nginx layer
      # so it is neglected in DEV
      - source: landingpage_merge_json_sh
        target: /docker-entrypoint.d/00.sh
        mode: 0555
    profiles:
      - search
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND_URL: ${BACKEND_HTTPS_URL:-http://backend.localhost}
      FRONTEND_URL: ${FRONTEND_HTTPS_URL:-http://localhost}
    labels:
      # Adding a label for traefik to learn which port to look for a service on
      - traefik.http.services.landingpage.loadbalancer.server.port=80

configs:
  landingpage_config_json:
    file: ./config/config.json
  landingpage_merge_json_sh:
    file: ${PWD}/entrypoints/merge_json.sh
