services:
  frontend:
    platform: linux/amd64
    image: ghcr.io/scicatproject/frontend:v4.4.1
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./config/config.json:/config/0.json
      - ./config/config.${BE_VERSION:-v4}.json:/config/1.json
      - ${PWD}/entrypoints/loop_entrypoints.sh:/usr/local/bin/loop_entrypoints.sh
      # This is numbered 1 (and not 0) as in the DEV config, which
      # inherits from this, it must be run after the git_init
      - ./entrypoints/merge_json.sh:/docker-entrypoints/1.sh
    entrypoint: loop_entrypoints.sh
    command: nginx -g "daemon off;"
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)
    restart: on-failure
    environment:
      BACKEND_URL: ${BACKEND_HTTPS_URL:-http://backend.localhost}
