services:
  frontend:
    image: ghcr.io/scicatproject/frontend:v5.7.0
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ${PWD}/entrypoints/merge_json.sh:/post_start/merge_json.sh
      - ./config/config.json:/config/config.0.json
      - ./config/config.oidc.json:/config/${OIDC_ENABLED:-.}config.1.json
      - ./config/config.ldap.json:/config/${LDAP_ENABLED:-.}config.2.json
      - ./config/config.jobs.json:/config/${JOBS_ENABLED:-.}config.3.json
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      # Adding a label for traefik to learn which port to look for a service on
      - traefik.http.services.frontend.loadbalancer.server.port=8080
    healthcheck:
      test: curl -f 'http://127.0.0.1:8080'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
    environment:
      CONFIG_FILE: config.override.json
      BACKEND_URL: ${BACKEND_HTTPS_URL:-http://backend.localhost}
    post_start:
      - command: /post_start/merge_json.sh
        user: root
