api:
  insecure: true

providers:
  docker: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  leresolver:
    acme:
      storage: /letsencrypt/acme.json
      email: mail@example.com
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
