services:
  backend:
    configs:
      # wait for kecyloak to get certificate
      - source: backend_v4_sleep_sh
        target: /docker-entrypoints/00.sh
        mode: 0555

configs:
  backend_v4_sleep_sh:
    file: ./entrypoints/sleep.sh
