services:
  proxy:
    image: traefik:2.11
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./config/.env
    labels:
      - traefik.http.services.proxy.loadbalancer.server.port=8080
