services:
  proxy:
    image: traefik:2.11
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/config.yaml:/etc/traefik/traefik.yaml:ro
      - letsencrypt_proxy_data:/letsencrypt

volumes:
  letsencrypt_proxy_data:
    driver: local
