services:
  frontend:
  # pinned to v4.7.0 because FE>v5 is not compatible with BE v3
    image: ghcr.io/scicatproject/frontend:v4.7.0
    volumes:
      - ./config/config.v3.json:${CONFIG_DIR}/config.override.0.json
