services:
  archivemock:
    build: https://github.com/SwissOpenEM/ScicatArchiveMock.git
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_healthy
    environment:
      SCI_URL: "http://backend:3000/api/v3/"
      SCI_USER: "admin"
      SCI_PW: "2jf70TPNZsS"
      RMQ_URL: "rabbitmq"
      RMQ_USER: "guest"
      RMQ_PW: "guest"
