services:
  proxy:
    image: traefik:v3.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt_proxy_data:/letsencrypt
    env_file:
      - ./config/.env
      - ./config/.tls.env
    labels:
      - traefik.http.services.proxy.loadbalancer.server.port=8080
    restart: on-failure

volumes:
  letsencrypt_proxy_data:
    driver: local
