services:
  docs:
    image: squidfunk/mkdocs-material:9.7
    volumes:
      - ${PWD}/.github/mkdocs/:/config/github-mkdocs
      - ./entrypoints/serve.sh:/usr/local/bin/serve.sh
      - ./config/index.md:/docs/index.md
      - ./config/external-links.md:/docs/external-links.md
    restart: on-failure
    entrypoint: /usr/local/bin/serve.sh
    environment:
      CONFIG_DIR: /config/github-mkdocs
      PYTHONDONTWRITEBYTECODE: 1
