services:
  backend:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-remote
    build:
      target: dev
    volumes:
      - ./config/functionalAccounts.dev.json:/home/node/app/functionalAccounts.json
    env_file:
      - ./config/.dev.env
    healthcheck:
      retries: 20
      interval: 1m

volumes:
  v4_dev:
    driver: local
