include:
  - ./compose.base.yaml
  - ../../..${ELASTIC_ENABLED:+/backend/services/v4}/compose${ELASTIC_ENABLED:+.elastic}.yaml
  - ../../..${LDAP_ENABLED:+/backend/services/v4}/compose${LDAP_ENABLED:+.ldap}.yaml
