services:
  backend:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-remote
    build:
      target: dev
    volumes:
      - ./config/functionalAccounts.dev.json:/home/node/app/functionalAccounts.json
      - ./config/.dev.env:/home/node/app/test/config/.env.override
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dev-dacat-next
      DEV: ${DEV}
    healthcheck:
      retries: 20
      interval: 1m

volumes:
  v4_dev:
    driver: local
