include:
  - ../rabbitmq/compose.yaml
  - .${S3_BROKER_ENABLED:+/}compose.s3-broker.yaml

services:
  backend:
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./config/jobConfig.yaml:/home/node/app/jobConfig.yaml
    env_file:
      - ./config/.jobs.env
