services:
  backend:
    extends:
      file: ${PWD}/services/compose.dev.yaml
      service: node-app-from-remote
    build:
      target: dev
    configs:
      - source: backend_v4_functional_accounts_dev_json
        target: /home/node/app/functionalAccounts.json
      - source: backend_v4_dev_env
        target: /home/node/app/test/config/.env.override
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dev-dacat-next
      DEV: ${BACKEND_DEV:+true}
    healthcheck:
      retries: 20
      interval: 1m

volumes:
  v4_dev:
    driver: local

configs:
  backend_v4_functional_accounts_dev_json:
    file: ./config/functionalAccounts.dev.json
  backend_v4_dev_env:
    file: ./config/.dev.env
