services:
  mongodb:
    image: mongo:8.0
    volumes:
      - backend${BE_VERSION:-v4}_mongodb_data:/data/db
      - ./config/init.sh:/init.sh:ro
      - ./config/seed:/seed
    labels:
      # Adding a label to keep this service out of traefik
      - traefik.enable=false
    environment:
      BE_VERSION: ${BE_VERSION:-v4}
      DEV: ${BACKEND_DEV:+dev-}
    restart: on-failure
    post_start:
      - command: /init.sh

volumes:
  backendv3_mongodb_data:
    driver: local
  backendv4_mongodb_data:
    driver: local
