services:
  searchapi:
    environment:
      NODE_ENV: development
      GITHUB_REPO: https://github.com/SciCatProject/panosc-search-api.git
    volumes:
      # These prevents git unpushed changes from being lost on container restart
      - searchapi_dev:/home/node/app
      # These volumes allow to run init scripts before running the service
      - ${PWD}/entrypoints/loop_entrypoints.sh:/usr/local/bin/loop_entrypoints.sh
      - ${PWD}/entrypoints/infinite_loop.sh:/usr/local/bin/infinite_loop.sh
      - ${PWD}/entrypoints/setup_git.sh:/docker-entrypoints/0.sh
      - ${PWD}/entrypoints/npm_ci.sh:/docker-entrypoints/1.sh
      - ./entrypoints/tests.sh:/docker-entrypoints/2.sh
    entrypoint:
      - loop_entrypoints.sh
      # This is the NODE original entrypoint
      - docker-entrypoint.sh
    command: infinite_loop.sh
    labels:
      - traefik.http.services.searchapi.loadbalancer.server.port=3000
    healthcheck:
      test: pgrep -f "/bin/sh /usr/local/bin/infinite_loop.sh"
    user: root

volumes:
  searchapi_dev:
    driver: local
