plugins:
  -
    - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
        - type: docs
          release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  -
    - '@semantic-release/exec'
    - publishCmd: echo "tag=${nextRelease.gitTag}" >> $GITHUB_ENV
