plugins:
  -
    - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
        - type: docs
          release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  -
    - '@semantic-release/exec'
    - publishCmd: |
        RAW_PATH="ghcr.io/${GITHUB_REPOSITORY}"
        IMAGE_PATH="${RAW_PATH,,}"
        docker compose push-bundle ghcr.io/$IMAGE_PATH:${nextRelease.version} \
        && docker compose push-bundle ghcr.io/$IMAGE_PATH:latest
    - successCmd: echo "tag=${nextRelease.gitTag}" >> $GITHUB_OUTPUT
