services:
  mongodb:
    image: mongo:7.0
    volumes:
      - "mongodb_data:/data/db"
      - "../seed_db/init.js:/docker-entrypoint-initdb.d/init.js"
      - "../seed_db/seed:/seed"

volumes:
  mongodb_data:
    driver: local
