name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      # v6
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50  # yamllint disable-line rule:line-length
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
