name: Docker Compose CI

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changed-files.outputs.src_all_modified_files }}
      be_version_values: ${{
          steps.changed-files.outputs.v3_all_modified_files
          && '["v3","v4"]' || '["v4"]'
        }}
      opensearch_values: ${{
          steps.changed-files.outputs.opensearch_all_modified_files
          && '["","opensearch"]' || '[""]'
        }}
      jobs_values: ${{
          steps.changed-files.outputs.jobs_all_modified_files
          && '["","jobs"]' || '[""]'
        }}
      ldap_values: ${{
          steps.changed-files.outputs.ldap_all_modified_files
          && '["","ldap"]' || '[""]'
        }}
      oidc_values: ${{
          steps.changed-files.outputs.oidc_all_modified_files
          && '["","oidc"]' || '[""]'
        }}
      dev_values: ${{
          steps.changed-files.outputs.dev_all_modified_files
          && '["","dev"]' || '[""]'
        }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Get changed files
        id: changed-files
        # v47
        uses: >-
          tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files_yaml_from_source_file: .github/changed_files.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    runs-on: ubuntu-latest
    needs:
      - changes
      - lint
    if: >
        ! failure()
        && ! cancelled()
        && needs.changes.outputs.src
    strategy:
      matrix:
        BE_VERSION: ${{ fromJson(needs.changes.outputs.be_version_values) }}
        OPENSEARCH_ENABLED: ${{
            fromJson(needs.changes.outputs.opensearch_values)
          }}
        JOBS_ENABLED: ${{ fromJson(needs.changes.outputs.jobs_values) }}
        LDAP_ENABLED: ${{ fromJson(needs.changes.outputs.ldap_values) }}
        OIDC_ENABLED: ${{ fromJson(needs.changes.outputs.oidc_values) }}
        DEV: ${{ fromJson(needs.changes.outputs.dev_values) }}
        GENERATE_SDK: ['']
        exclude:
          - OPENSEARCH_ENABLED: opensearch
            BE_VERSION: v3
        include:
          - BE_VERSION: v4
            DEV: dev
            GENERATE_SDK: generate_sdk
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Test compose.yaml
        id: docker_up
        continue-on-error: ${{ matrix.GENERATE_SDK == 'generate_sdk' }}
        run: |-
          export JOBS_ENABLED=${{ matrix.JOBS_ENABLED }}
          export OPENSEARCH_ENABLED=${{ matrix.OPENSEARCH_ENABLED }}
          export LDAP_ENABLED=${{ matrix.LDAP_ENABLED }}
          export OIDC_ENABLED=${{ matrix.OIDC_ENABLED }}
          export BE_VERSION=${{ matrix.BE_VERSION }}
          export DEV=${{ matrix.DEV }}
          export DEV_BBACKUP=${DEV}
          export GENERATE_SDK=${{ matrix.GENERATE_SDK }}
          DEV_OVERLAY=${GENERATE_SDK:+.github/compose.sdk.test.yaml}
          DEV_OVERLAY=${DEV_OVERLAY:-.github/compose.dev.test.yaml}
          PROFILE=${GENERATE_SDK:+none}
          PROFILE=${PROFILE:-'*'}
          docker compose --profile "$PROFILE" \
            -f compose.yaml ${DEV:+-f "$DEV_OVERLAY"} \
            up --wait --wait-timeout 1200 \
            || {
              docker compose ps --all --format json \
                | jq -r 'select((.Health != "" and .Health != "healthy")
                    or .State != "running") | .Service' \
                | while read -r service; do
                  echo "Logs for $service"
                  docker compose logs "$service"
                done
              exit 1
            }
      - name: Check if frontend broke on the new SDK
        id: sdk_check
        if: >-
          steps.docker_up.outcome == 'failure' &&
          matrix.GENERATE_SDK == 'generate_sdk'
        run: |
          STATUS=$(docker compose ps --format '{{.Health}}' frontend)
          [ "$STATUS" != "healthy" ] \
            && echo "sdk_error=true" >> "$GITHUB_OUTPUT"
      - name: Fail on non-SDK failure
        if: >-
          steps.docker_up.outcome == 'failure' &&
          matrix.GENERATE_SDK == 'generate_sdk' &&
          steps.sdk_check.outputs.sdk_error != 'true'
        run: |
          echo "compose up failed for a reason unrelated to SDK generation."
          exit 1
      - name: Add Failure Label
        if: steps.sdk_check.outputs.sdk_error == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label \
          "sdk-failed"
      - name: Cleanup Failure Label
        if: >-
          steps.docker_up.outcome == 'success' &&
          matrix.GENERATE_SDK == 'generate_sdk'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remove the label if it exists (ignore error if it's already gone)
          gh pr edit ${{ github.event.pull_request.number }} \
          --remove-label "sdk-failed" || true
  tests-status:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - changes
      - lint
      - test
    steps:
      - name: Evaluate Results
        run: |
          RES="${{ join(needs.*.result, ' ') }}"
          [[ $RES =~ "failure" || $RES =~ "cancelled" ]] && exit 1 || exit 0
