name: Docker Compose CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install 'yamllint'
        run: sudo apt-get install -y yamllint
      - name: Lint YAML files
        run: yamllint -c .github/yamllint_config.yaml .
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install 'jsonlint'
        run: sudo apt install python3-demjson
      - name: Lint JSON files
        run: >-
          git ls-files --exclude='*.json' --ignored -c -z |
          xargs -0r jsonlint -s --allow=non-portable
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install 'shellcheck' and 'git'
        run: sudo apt install shellcheck git
      - name: Lint shell files ([ba]sh scripts)
        run: >-
          git ls-files --exclude='*.sh' --ignored -c -z | xargs -0r shellcheck
  test:
    runs-on: ubuntu-latest
    needs:
      - yaml-lint
      - json-lint
      - shell-lint
    strategy:
      matrix:
        BE_VERSION: [v3, v4]
    steps:
      - uses: actions/checkout@v4
      - name: Test docker-compose.yaml
        run: |-
          export BE_VERSION=${{ matrix.BE_VERSION }}
          docker compose up --wait --wait-timeout 300
