name: Create release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: .github/semantic-release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install --no-package-lock
      - name: Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - uses: SciCatProject/scicatlive/.github/actions/mkdocs-pages@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          push: true
          docs_folder: ''
          TAG: ${{ steps.semantic-release.outputs.tag }}
